### ISSUE TITLE
Hackernoon article images mostly replaced with author's avatar

### ISSUE THREAD

**Issue by aminamos** [learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions#10]
It looks like there are supposed to be images of example code, but no code exists. Article link: https://hackernoon.com/javascript-and-functional-programming-pt-2-first-class-functions-4437a1aec217

Section: Conclusion
Title: First Class Functions Hackernoon

**Comment by sylwiavargas** [comment]
Thank you for your comment! We have updated the readme.
