### ISSUE TITLE
`exerciseDog` issues

### ISSUE THREAD

**Issue by timothylevi** [learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions#4]
The [last test in this lab](https://github.com/learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions/blob/8a1db9ff793b510a2603b503c3b4037f7b81eea7/test/indexTest.js#L38) calls for a student to "[create] a function exerciseDog that returns the full day's dog exercise routine". 

It's unclear from the README, test, and solution what this function should actually do. In the test file, the test itself is not much different from the previous test, and doesn't assert that the function `exerciseDog` exists nor that it is called. In the solution file, the `exerciseDog` function loops over a variable `functionsArray` that doesn't exist. In the README, it says "A function called exerciseDog with default parameters set that iterates over the array and returns the full exercise routine."

#staff

**Comment by sgharms** [comment]
@timothylevi I updated the master and solution branch and I think this has been dealt with now. Please confirm and reply and / or close this issue.
