### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions#6]
I took some time off, and I'm reviewing the js section now that the new labs are in, so I can get ready to finish my project.

* clarify whether this is a lesson or lab -- there is testing for it, so it should be called a lab? It's not clear what one should DO at the end. 

* the solution code uses map -- which hasn't been introduced yet, and students wouldn't know to use it. Really hard to clear the tests if you don't peek in. 

* In general, it's a big jump from the lesson info to completing the tests -- assigning  a function to a variable hasn't been covered, nor has how to manipulate returns. I know that one of the problems in the last iteration of this section was the too-large spread between lesson and lab, and this one may need some reworking to accomplish that. 

Up till now, though, the lessons and labs have been such an awesome improvement over what they were!

**Comment by sgharms** [comment]
1. Updated in 3e8a6760d5
2. `solution` branch updated which fixes the 2nd and 3rd bullets.

Thanks for your insight.
