### ISSUE TITLE
Fns As First Class Data: Array O' Functions instruction issue

### ISSUE THREAD

**Issue by jehough** [learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions#7]
Within the lesson in the Create an Array 'o functions section it gives the instructions to use console.log() when building the functions but the tests require you to use return.

Also, the label for the function in the lesson is walktoPark but in tests is walkToPark.

**Comment by sgharms** [comment]
1. I believe your concern here was covered in

https://github.com/learn-co-curriculum/fewpjs-fns-as-first-class-data-array-o-functions/blame/master/README.md#L52-L53

2. I can't replicate your note about the label. Looking at the output of a `grep`:

![image](https://user-images.githubusercontent.com/50019/66145325-98288600-e5d8-11e9-983b-d999c6702531.png)

I can't see that we say `walktopark` in any inconsistent casing. The case you mention specifically, I don't see in our canonical source:

![image](https://user-images.githubusercontent.com/50019/66145385-baba9f00-e5d8-11e9-9b91-3b36359aa888.png)

Can you clarify?

Or, is it possible your copy didn't have this material (maybe a replication bug)?

**Comment by sgharms** [comment]
I think this last update addresses your concerns, and thus I'm going to close. If something still isn't right, please re-open.
